export { default as Navbar } from "./navbar/navbar";
export { default as Footer } from "./footer/footer";
export { default as Hero } from "./hero/hero.astro";
export { default as FeaturesComponent } from "./features/features";
export { default as LogoCloud } from "./logocloud/logocloud";
export { default as Stats } from "./stats/stats";
export { default as PricingComponent } from "./pricing/pricing";
export { default as AboutComponent } from "./about/about";
export { default as SubscribeComponent } from "./subscribe/subscribe";